In [1]:
import pandas as pd
import numpy as np

from library1 import *

In [2]:
path = 'D:\KU\mlops\data'
train_chg = pd.read_csv(path + '/data/raw_data/train/1000_chg.csv')
train_dchg = pd.read_csv(path + '/data/raw_data/train/1000_dchg.csv')
test = pd.read_csv(path + '/data/raw_data/test/Test05_NG_chg.csv')

In [3]:
# chg 데이터와 dchg 데이터 합치기
train = pd.concat([train_chg, train_dchg])
train = train.reset_index(drop = True)

In [4]:
# 파이프라인 이용해서 전처리 (library1의 pipeline_model class에 속한 코드)
preprocess_pipe = Pipeline([
    ('feature_selector', VolTempSelector('M')),
    ('missing_value', handleMissingValue()),
    ('siff_smooth_df', DiffSmooth(0, 0, 0)),
    ('pca', PCA(n_components = 3)),
    ('minmax_scaler', MinMaxScaler()),
    ('component_selector', ComponentSelector(3))
])

In [5]:
preprocess_pipe.fit_transform(train)

              0         1         2
0      0.998576  0.999115  0.192774
1      0.998621  0.998883  0.165573
2      0.998620  0.998942  0.165567
3      0.998576  0.999123  0.192773
4      0.999189  1.000000  0.214066
...         ...       ...       ...
11362  0.097391  0.543434  0.039768
11363  0.097391  0.543451  0.039765
11364  0.098000  0.544580  0.018894
11365  0.097396  0.543462  0.050241
11366  0.097391  0.543442  0.039767

[11367 rows x 3 columns]

In [6]:
preprocess_pipe.fit_transform(test)

             0         1         2
0     0.999474  0.599393  0.124659
1     0.999997  0.600814  0.096741
2     1.000000  0.597703  0.187976
3     0.999464  0.597970  0.079366
4     0.999486  0.599486  0.111835
...        ...       ...       ...
5011  0.001073  0.994540  0.596380
5012  0.000547  0.990520  0.691322
5013  0.000527  0.991591  0.632839
5014  0.000519  0.992506  0.632940
5015  0.000000  0.988305  0.659860

[5016 rows x 3 columns]